SUPABASE_URL = "https://youapfxvnmltuzanhdky.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvdWFwZnh2bm1sdHV6YW5oZGt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzODk3ODMsImV4cCI6MjA3MTk2NTc4M30.E6homMpW7TgR0lwBilCclUvzuBLef3Y_3yX3VRXbHMM"
SUPABASE_BUCKET = "festival-images"
